### ISSUE TITLE
AppsflyerModule.Start() fails with 401 Unauthorized error

### ISSUE THREAD

**Issue by huytc** [AppsFlyerSDK/appsflyer-native-pc-unity-sample-app#5]
I've got a native PC Unity app that uses AppsFlyer.
I've tried starting AppsFlyer like this:
```c#
AppsflyerModule afm = new AppsflyerModule(DEV_KEY,  APP_ID , this);
afm.Start();
```
Where:
- `DEV_KEY` is the dev key I got from AppsFlyer HQ.
- `APP_ID` is my app ID on the AppsFlyer HQ (I've tried both with and without the `nativepc-` prefix).

I've also tried with and without sandbox mode.
But it always ends up with a 401 Unauthorized error in the logs.

**Comment by qbit86** [comment]
The same, I'm getting `ProtocolError` with "HTTP/1.1 401 Unauthorized".
@huytc Have you had any success with this problem?

**Comment by huytc** [comment]
You can check out the fork on my GitHub. IIRC what I ended up doing was
changing "timestamp" to number type. Also, an app has to wait like a few
hours after creation before you can send events for that app.

**Comment by huytc** [comment]
@qbit86 What I ended up doing was:
- Waited a few hours after app creation before sending events for that app (yes, it only works after a few hours).
- Changed `timestamp` from `string` to `long`.
I'm not sure the timestamp change matters though, so maybe you can experiment with it.

**Comment by qbit86** [comment]
@huytc Thanks!

> I'm not sure the timestamp change matters though, so maybe you can experiment with it.

I've tried changing the type (and therefore serialization) of the `timestamp` field, but it doesn't affect the error "HTTP/1.1 401 Unauthorized" 🤷‍♂️

**Comment by huytc** [comment]
@qbit86 In that case I guess it's something on the server side then, not an error with the SDK itself. We probably have to wait a certain amount of time after app creation before sending events.

**Comment by qbit86** [comment]
> In that case I guess it's something on the server side then, not an error with the SDK itself.

Well, it's not a problem with the SDK, because this approach does not use any SDKs, it sends direct POST requests via web API.
The issue is probably in signing the message with HMACSHA256, but I don't know how to debug it. No diagnostics available.

**Comment by huytc** [comment]
@qbit86 My bad, what I mean by "SDK" is the "Module" provided in this repo. What I'm trying to say is that the 401 error goes away after a few hours. So there shouldn't be anything wrong with the code here, and this issue can probably be closed.

**Comment by gilmor-af** [comment]
Hello @qbit86 & @huytc, 401 error indicates authorization issue, it might occur while using a wrong devkey/appid, if it happens again please open a ticket to our support
https://support.appsflyer.com/hc/en-us?p=marketers

**Comment by qbit86** [comment]
> error indicates authorization issue, it might occur while using a wrong devkey/appid

@gilmor-af In my case, it was an incorrect URL `https://events.appsflyer.com/.../nativepc/` instead of the correct `https://events.appsflyer.com/.../steam/`

Thanks for your help!
