### ISSUE TITLE
something about af_counter and RequestType?

### ISSUE THREAD

**Issue by LOUTINIER** [AppsFlyerSDK/appsflyer-native-pc-unity-sample-app#7]
`af_counter` is only `>=` 2 then requests `SESSION_REQUEST` but start from 0, which causes the first two launches both request `FIRST_OPEN_REQUEST`, is this a bug or anything?

**Comment by gilmor-af** [comment]
Hello, 
This is not a bug, the first two launches are designated to be FIRST_OPEN_REQUEST
